remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

title: Godot Procedural City
tagline: Procedural City Generation Done Though Raymarching, Entirely on the GPU
description: Procedural City Generation Done Though Raymarching, Entirely on the GPU
